---
repos:
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
      - id: black-jupyter
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        files: ^alsa/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: "^tests/sample_data/kl5_test_data/.*$"
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=50000"]
