name: alsa
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alabaster=0.7.12
  - appdirs=1.4.4
  - argh=0.26.2
  - arrow=1.1.0
  - astor=0.8.1
  - astroid=2.5.6
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.6
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - binaryornot=0.4.4
  - black=21.5b0
  - bleach=3.3.0
  - blinker=1.4
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cookiecutter=1.7.2
  - cryptography=3.4.7
  - curl=7.76.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.4.1
  - dataclasses=0.8
  - decorator=5.0.7
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.3
  - expat=2.3.0
  - fiona=1.8.19
  - flake8=3.8.4
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2021.4.0
  - future=0.18.2
  - gast=0.4.0
  - gdal=3.2.2
  - geopandas=0.9.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - google-auth=1.30.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.37.1
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imagecodecs=2021.3.31
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=4.0.1
  - importlib_metadata=4.0.1
  - inflection=0.5.1
  - intel-openmp=2021.2.0
  - intervaltree=3.0.2
  - ipykernel=5.5.4
  - ipython=7.23.1
  - ipython_genutils=0.2.0
  - isort=5.8.0
  - jedi=0.17.2
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jxrlib=1.1
  - kealib=1.4.14
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - keyring=23.0.1
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.76.1
  - libdeflate=1.7
  - libffi=3.3
  - libgdal=3.2.2
  - libglib=2.68.1
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libpng=1.6.37
  - libpq=13.2
  - libprotobuf=3.15.8
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - libzip=1.7.3
  - libzopfli=1.0.3
  - locket=0.2.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - msys2-conda-epoch=20160418
  - multidict=5.1.0
  - munch=2.5.0
  - mypy_extensions=0.4.3
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.3
  - numpy=1.20.2
  - numpydoc=1.1.0
  - oauthlib=3.0.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.13
  - pandocfilters=1.4.2
  - paramiko=2.7.2
  - parso=0.7.0
  - partd=1.2.0
  - pathspec=0.8.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.1
  - pixman=0.40.0
  - pluggy=0.13.1
  - pooch=1.3.0
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.2
  - poyo=0.5.0
  - proj=8.0.0
  - prompt-toolkit=3.0.18
  - protobuf=3.15.8
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=6.0.0
  - pyflakes=2.2.0
  - pygments=2.9.0
  - pyjwt=2.1.0
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.0.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python-slugify=5.0.2
  - python_abi=3.8
  - pytz=2021.1
  - pywavelets=1.1.1
  - pywin32=300
  - pywin32-ctypes=0.2.0
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qdarkstyle=3.0.2
  - qstylizer=0.2.0
  - qt=5.12.9
  - qtawesome=1.0.2
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - regex=2021.4.4
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rope=0.18.0
  - rsa=4.7.2
  - rtree=0.9.7
  - scikit-image=0.18.1
  - scipy=1.6.3
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.16.0
  - snappy=1.1.8
  - snowballstemmer=2.1.0
  - sortedcontainers=2.3.0
  - sphinx=3.5.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.35.5
  - tbb=2021.2.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.4.0
  - termcolor=1.1.0
  - testpath=0.4.4
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tifffile=2021.4.8
  - tiledb=2.2.8
  - tinycss2=1.1.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.3
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - ujson=4.0.2
  - unidecode=1.2.0
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - whichcraft=0.6.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.6.3
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  # For testing
  - pytest
  - pre-commit
  - pip:
      - joblib==1.0.1
      - mrcfile==1.3.0
      - ridge-detection==2.0.1
      - scikit-learn==0.24.2
      - simplejson==3.17.2
      - threadpoolctl==2.2.0