name: alsa
channels:
  - conda-forge
dependencies:
  - python=3.8.8
  - pip=21.1.1
  - geopandas=0.9.0
  - matplotlib=3.4.1
  - numpy=1.20.2
  - pandas=1.2.4
  - pillow=8.2.0
  - scikit-image=0.18.1
  - scipy=1.6.3
  - shapely=1.7.1
  - tensorflow=2.3.0
  - scikit-learn=1.0.2
  # For the command-line interface
  - typer=0.4.1
  - click=7.1.2
  # For testing
  - pytest=7.1.1
  - pre-commit=2.17.0
  - ipython=8.2.0
  - pip:
      - ridge-detection==2.0.1
