[tool.pytest.ini_options]
testpaths =[
    "tests",
    "alsa",
    ]
addopts = "--doctest-modules --disable-warnings"
doctest_optionflags =[
    "NUMBER",
    "NORMALIZE_WHITESPACE",
    ]

filterwarnings =[
    ]
